name: Lint, test & deploy on push
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dev-dependencies
        run: npm install --only=dev

      - name: Lint the code
        run: npm run lint
  build:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dev-dependencies
        run: npm install --only=dev
      
      - name: Build the code
        run: npm run build
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dev-dependencies
        run: npm install --only=dev

      - name: Test the code
        run: npm run test
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dev-dependencies
        run: npm install --only=dev

      - name: Deploy the code
        run: echo "Deploying the code..."
